### ISSUE TITLE
Common core?

### ISSUE THREAD

**Issue by bclinkinbeard** [Rich-Harris/lit-node#3]
`lit`, `lit-node` and the rollup plugin all appear to reimplement the core idea of evaluating code embedded in Markdown. Is it premature to consider the development of one canonical engine that gets wrapped to add various DXes? Wrapper for CLI support, wrapper for file IO, etc? But the core would be a JS API that accepts a string and returns... the pure JS, I guess? That way eval could be delayed, customized, etc.

Thoughts?

**Comment by Rich-Harris** [comment]
Ordinarily I would agree. In this case, though, I think it might make sense to reimplement it each time:

* `lit` is a language-agnostic bash program, which doesn't even require Node to be installed
* `lit-node` obviously *does* require Node, and since there's overhead involved in spinning up a separate process to do the transformation, it makes sense to implement it in JS. Also, it has JS-specific features like ignoring non-JS code blocks and wrapping the script in an `async` function
* `rollup-plugin-markdown` shouldn't do the `async` thing, but it *does* need to generate a sourcemap (just because Rollup expects one, otherwise it assumes that it can't generate a correct sourcemap for the bundle) that would just be useless overhead if `lit-node` did it. At present, that's done with `magic-string`, which `lit-node` shouldn't depend on.

**Comment by bclinkinbeard** [comment]
Gotcha, makes sense. Thanks for the explanation.
